---
title: "Project"
format: html
execute: 
  echo: true      # change to true to show the code
code-fold: false  # change to true to fold the code chunks
---

```{r}
library(ggplot2)
library(ggiraph)
library(dplyr)
library
library(stringr)
salary_potential <- read.csv("salary_potential.csv")
regions <- read.csv("states.csv")
```

```{r}
regions <- regions %>%
  rename(state_name = State)

rsp <- salary_potential %>% 
full_join(regions, by = "state_name")
```

```{r}
#| fig-height: 15
#| fig-width: 10

q <- ggplot(rsp, aes(x = mid_career_pay, y = make_world_better_percent)) +
  geom_point_interactive(aes(tooltip = paste("College:", name, "<br>State:", state_name, "<br>Stem   Percentage:", stem_percent)), alpha = 0.5) +
  theme_minimal() +
  geom_smooth(method = "lm")

girafe(ggobj = q)
```

```{r}
#| fig-height: 15
#| fig-width: 10

q <- ggplot(rsp, aes(x = mid_career_pay, y = make_world_better_percent, size = stem_percent)) +
  geom_point_interactive(aes(tooltip = paste("College:", name, "<br>State:", state_name, "<br>Stem   Percentage:", stem_percent)), alpha = 0.5) +
  theme_minimal() +
  geom_smooth(method = "lm")

girafe(ggobj = q)
```

```{r}
rsp_cat <- rsp %>% 
  mutate(category = case_when(
    str_detect(name, "Medical") | str_detect(name, "Nurs") | str_detect(name, "Health") | str_detect(name, "Bellin") | str_detect(name, "Rush") | str_detect(name, "Samuel Merritt") ~ "Medical",
    str_detect(name, "Tech") | str_detect(name, "tech") ~ "Tech",
    str_detect(name, "Baptist") | str_detect(name, "Methodist") | str_detect(name, "Luther") | str_detect(name, "Advent") | str_detect(name, "Christian") | str_detect(name, "Franciscan")~ "Religious",
    str_detect(name, "Military") | str_detect(name, "United") ~ "Military",
    TRUE ~ "Other"
  ))
```

```{r}
#| fig-height: 15
#| fig-width: 10

p <- ggplot(rsp, aes(x = mid_career_pay, y = make_world_better_percent, color = Division)) +
  geom_point_interactive(aes(tooltip = paste("College:", name, "<br>State:", state_name, "<br>Stem   Percentage:", stem_percent)), alpha = 0.5) +
  theme_minimal() +
  facet_wrap(~Division) +
  geom_smooth(method = "lm")

girafe(ggobj = p)
```
```{r}
#| fig-height: 15
#| fig-width: 10

c <- ggplot(rsp_cat, aes(x = mid_career_pay, y = make_world_better_percent, color = category)) +
  geom_point_interactive(aes(tooltip = paste("College:", name, "<br>State:", state_name, "<br>Stem   Percentage:", stem_percent)), alpha = 0.5) +
  theme_minimal()
  
girafe(ggobj = c)
```
```{r}
#| fig-height: 15
#| fig-width: 10

s <- ggplot(rsp_cat, aes(x = mid_career_pay, y = make_world_better_percent, size = stem_percent, color = category)) +
  geom_point_interactive(aes(tooltip = paste("College:", name, "<br>State:", state_name, "<br>Stem   Percentage:", stem_percent)), alpha = 0.5) +
  theme_minimal() +
  facet_wrap(~category) +
  geom_smooth(method = "lm")

girafe(ggobj = s)
```
